### ISSUE TITLE
Firefox: Text Selectoed on drag

### ISSUE THREAD

**Issue by entrpyc** [entrpyc/fancy-navigation#1]
-Firefox latest

Dragging the navigation results in selecting the text in the <li> elements

**Comment by zahari00** [comment]
This can be fixed by adding CSS:
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
